version: '3.3'

services:
  db:
    image: postgres:14-alpine
    container_name: django-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django-web
    command: python manage.py runserver 0.0.0.0:8000
#    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
